package dev.hytalemodding.quality;

import com.hypixel.hytale.server.core.asset.type.item.config.Item;
import dev.hytalemodding.config.QualityConfig;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

/**
 * Utility class for item quality eligibility checks.
 *
 * Provides eligibility checks used by QualityRegistry and QualityAssigner.
 */
public final class QualityItemFactory {

    private QualityItemFactory() {} // Utility class, no instantiation

    /** Hardcoded default ignored prefixes (consumables, projectiles, etc.). */
    private static final String[] DEFAULT_IGNORED_PREFIXES = {
            "Weapon_Bomb",
            "Weapon_Arrow",
            "Weapon_Dart",
            "Weapon_Spellbook",
            "Tool_Feedbag",
            "Tool_Watering_Can"
    };

    /** Cached merged ignore set (built once from config + defaults). */
    private static Set<String> cachedIgnorePrefixes = null;

    /**
     * Initializes the ignore list from config. Call once at startup after
     * config is loaded, before scanning items.
     *
     * Config values are MERGED with hardcoded defaults so that newly added
     * defaults (e.g. Tool_Watering_Can added in v2.0.1) are always active
     * even if the server's config file was generated by an older version.
     */
    public static void initIgnoreList(@Nullable QualityConfig config) {
        Set<String> prefixes = new HashSet<>(Arrays.asList(DEFAULT_IGNORED_PREFIXES));
        if (config != null) {
            String[] configPrefixes = config.getIgnoredItemPrefixes();
            if (configPrefixes != null) {
                // Merge: keep hardcoded defaults AND add config values
                Collections.addAll(prefixes, configPrefixes);
            }
        }
        cachedIgnorePrefixes = prefixes;
        System.out.println("[RQC] Ignore list initialized with " + prefixes.size()
                + " prefixes: " + prefixes);
    }

    /**
     * Checks if an item ID is on the ignore list (matches any prefix).
     *
     * Hytale prefixes some item IDs with '*' for state variants
     * (e.g. "*Tool_Watering_Can_State_Filled_Water"). We strip the
     * leading '*' before matching so that the prefix "Tool_Watering_Can"
     * correctly catches all state variants.
     */
    public static boolean isIgnored(@Nonnull String itemId) {
        Set<String> prefixes = cachedIgnorePrefixes;
        if (prefixes == null) {
            // Fallback if not initialized — use hardcoded defaults
            prefixes = new HashSet<>(Arrays.asList(DEFAULT_IGNORED_PREFIXES));
        }
        // Strip Hytale's '*' state-variant prefix before matching
        String normalized = itemId.startsWith("*") ? itemId.substring(1) : itemId;
        for (String prefix : prefixes) {
            if (normalized.startsWith(prefix)) return true;
        }
        return false;
    }

    /**
     * Checks if an item is eligible for quality variants.
     * An item qualifies if it's a weapon, armor, or tool AND not on the ignore list.
     */
    public static boolean isEligibleForQuality(@Nonnull String itemId, @Nonnull Item item) {
        if (isIgnored(itemId)) return false;
        return isTypeEligible(item);
    }

    /**
     * Type-only check: returns true if the Item is a weapon, armor, or tool.
     * Does NOT check the ignore list — use {@link #isEligibleForQuality(String, Item)}
     * for full eligibility.
     */
    private static boolean isTypeEligible(@Nonnull Item item) {
        if (item.getWeapon() != null) return true;
        if (item.getArmor() != null) return true;
        if (item.getTool() != null) return true;
        if (item.getBlockSelectorToolData() != null) return true;

        return false;
    }
}
