# PowerShell script to add exclusion lists to the config file generated by Hytale
# RomnasQualityCrafting - Configuration Fixer

$configPath = "config\RomnasQualityCrafting.json"
$templatePath = "src\main\resources\RomnasQualityCrafting.json"

Write-Host "=== RomnasQualityCrafting Configuration Fixer ===" -ForegroundColor Cyan
Write-Host ""

# Check if config file exists
if (-not (Test-Path $configPath)) {
    Write-Host "Error: Config file $configPath does not exist." -ForegroundColor Red
    Write-Host "Please start the server once first to generate the file." -ForegroundColor Yellow
    Read-Host "Press Enter to exit"
    exit
}

Write-Host "Config file found: $configPath" -ForegroundColor Green

# Read config file
try {
    $configContent = Get-Content $configPath -Raw | ConvertFrom-Json
} catch {
    Write-Host "Error reading config file: $_" -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit
}

# Check if lists already exist
if ($configContent.PSObject.Properties.Name -contains "ExcludedIdPrefixes" -and 
    $configContent.PSObject.Properties.Name -contains "ExcludedItems") {
    Write-Host ""
    Write-Host "Exclusion lists already exist in the config file." -ForegroundColor Yellow
    $overwrite = Read-Host "Do you want to overwrite them with default values? (y/n)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "Operation cancelled." -ForegroundColor Yellow
        Read-Host "Press Enter to exit"
        exit
    }
}

# Define default lists
$excludedIdPrefixes = @(
    "Bench_",
    "Weapon_Arrow_",
    "Weapon_Bomb_",
    "Weapon_Dart_",
    "Weapon_Grenade_",
    "Weapon_Kunai_",
    "Debug_",
    "Test_",
    "Template_"
)

$excludedItems = @(
    "Weapon_Bomb",
    "Farming_Collar",
    "Halloween_Broomstick",
    "Tool_Feedbag",
    "Tool_Fertilizer",
    "Tool_Map"
)

# Add lists to config file
$configContent | Add-Member -MemberType NoteProperty -Name "ExcludedIdPrefixes" -Value $excludedIdPrefixes -Force
$configContent | Add-Member -MemberType NoteProperty -Name "ExcludedItems" -Value $excludedItems -Force

# Create backup
$backupPath = "$configPath.backup"
Copy-Item $configPath $backupPath -Force
Write-Host ""
Write-Host "Backup created: $backupPath" -ForegroundColor Green

# Write updated config file
try {
    $configContent | ConvertTo-Json -Depth 10 | Set-Content $configPath -Encoding UTF8
    Write-Host ""
    Write-Host "Config file updated successfully!" -ForegroundColor Green
    Write-Host ""
    Write-Host "The following lists have been added:" -ForegroundColor Cyan
    Write-Host "  - ExcludedIdPrefixes: $($excludedIdPrefixes.Count) prefixes" -ForegroundColor White
    Write-Host "  - ExcludedItems: $($excludedItems.Count) items" -ForegroundColor White
} catch {
    Write-Host ""
    Write-Host "Error writing config file: $_" -ForegroundColor Red
    Write-Host "Restoring backup..." -ForegroundColor Yellow
    Copy-Item $backupPath $configPath -Force
}

Write-Host ""
Write-Host "Done!" -ForegroundColor Green
Read-Host "Press Enter to exit"
